Added a batch mode to the ldap-disable-user script

diff --git a/ldap-disable-user b/ldap-disable-user
--- a/ldap-disable-user
+++ b/ldap-disable-user
@@ -1,12 +1,16 @@
 #!/bin/sh
 # ldap-disable-user - disable/enable user LDAP account  
-# Written by Wei Feinstein
-# Last modified 4/8/2017
+# Written by Wei Feinstein and Le Yan
+# Last modified 10/30/2019
+
+# Change 10/30/2019
+# Added a batch mode to disable inactive/ineligible users 
 
 export NSS_HASH_ALG_SUPPORT=+MD5
 admid=$(who am i | awk '{print $1}')
 timestamp=`date +%F`
 
+# The admin, reviewer and training accounts must be handled manually.
 exclude_hpc=(train gold nandakum ftsai jembrown moreno walkertr sjpark autoaccounts directory_test dquery ldap02 ldap03 ldapReplicants loadleveler redminequery xymonquery)
 exclude_loni=(train gold ramu michal cice cortez csumma blevins  autoaccounts jabber l1f1u02 l6l1u01_ldap l6l1u02_ldap ldap02 ldap03 ldap04 ldapReplicants loadleveler lonimail cysuser lonircs otrsuser)
 
@@ -17,12 +21,14 @@ Usage(){
        echo " "
        echo "   params:"
        echo "  -u  uid"
+       echo "  -b  <file>"
        echo "  -g  [hpc/loni/xsede/teragrid]"
        echo "  -o  [disable/reenable]"	
        echo "  -h  - get this help message"
        echo " "
        echo "  example  "
        echo "  sudo /admin/scripts/ldap-disable-user -u shpyang -o reenable -g loni"
+       echo "  sudo /admin/scripts/ldap-disable-user -b users.to.be.disabled -o disable -g loni"
        echo " "
 }
 Generate_ldif_loni_dis() {
@@ -168,7 +174,7 @@ Generate_ldif_hpc_react() {
         ldif=$(echo $ldif"\n"newsuperior: ou=$user,ou=People,dc=hpc,dc=lsu,dc=edu"\n")
 }
 
-Deactivate_accounts(){
+Assemble_modification(){
 
 	if [[ $category == "loni" && $action == "disable" ]]; then
 		Generate_ldap_ldif=Generate_ldif_loni_dis
@@ -196,6 +202,35 @@ Genpasswd(){
 	epasswd=$(echo "$passwd" | openssl passwd -1 -stdin)
 	eepasswd=$(echo "$epasswd" | openssl passwd -1 -stdin)
 }
+
+Getpasswd(){
+
+
+        index=3
+        results="ldap_bind"
+	passwd=
+#       while [[ `echo "$results" |grep "Invalid credentials"` &&  $index >0 ]];  blank passwd added
+        while [[ `echo "$results" |grep "ldap_bind"` &&  $index >0 ]];
+        do
+                echo Type password to access LDAP, followed by return
+		read -es ldappasswd
+                if [[ $category == "hpc" ]]; then
+                        results=$(ldapsearch -LLL -ZZ -x -h ldap01.hpc.lsu.edu  -D uid=$admid,ou=Admins,ou=People,dc=hpc,dc=lsu,dc=edu -w "$ldappasswd" -b dc=hpc,dc=lsu,dc=edu "uid=$admid"  2>&1)
+                else
+                        #results=$(ldapsearch -LLL -ZZ -x -h ldap01.sys.loni.org  -D uid=$admid,ou=People,ou=Admins,dc=loni,dc=org -W -b dc=loni,dc=org "uid=$uid" 2>&1)
+                        results=$(ldapsearch -LLL -ZZ -x -h lonildap01.hpc.lsu.edu  -D uid=$admid,ou=People,ou=Admins,dc=loni,dc=org -w "$ldappasswd" -b dc=loni,dc=org "uid=$admid" 2>&1)
+                fi
+                index=$(echo $index-1|bc)
+        done
+	echo $result
+
+        if [[ `echo "$results" |grep "ldap_bind"` ]]; then
+                echo Passwd failed 3 times!$'\n'
+                exit 1
+        fi
+
+}
+
 Check(){
        
         #exlude predefined user accounts
@@ -203,7 +238,7 @@ Check(){
         exclude_list=$(echo ${exclude_arr[@]})
         if [[ `echo $exclude_list |grep -w $uid` && "$action" == "disable" ]]; then
 		echo $uid is in the allocation committee, abort! $'\n'
-		exit 1
+		Stop	
 	fi
 	
 	index=3
@@ -211,40 +246,40 @@ Check(){
 #    	while [[ `echo "$results" |grep "Invalid credentials"` &&  $index >0 ]];  blank passwd added
     	while [[ `echo "$results" |grep "ldap_bind"` &&  $index >0 ]];
     	do
-        	echo Type password to access LDAP, followed by return
-        if [[ $category == "hpc" ]]; then
-                results=$(ldapsearch -LLL -ZZ -x -h ldap01.hpc.lsu.edu  -D uid=$admid,ou=Admins,ou=People,dc=hpc,dc=lsu,dc=edu -W -b dc=hpc,dc=lsu,dc=edu "uid=$uid"  2>&1)
-       	else
-                #results=$(ldapsearch -LLL -ZZ -x -h ldap01.sys.loni.org  -D uid=$admid,ou=People,ou=Admins,dc=loni,dc=org -W -b dc=loni,dc=org "uid=$uid" 2>&1)
-                results=$(ldapsearch -LLL -ZZ -x -h lonildap01.hpc.lsu.edu  -D uid=$admid,ou=People,ou=Admins,dc=loni,dc=org -W -b dc=loni,dc=org "uid=$uid" 2>&1)
-        fi
-
-        index=$(echo $index-1|bc)
+#        	echo Type password to access LDAP, followed by return
+        	if [[ $category == "hpc" ]]; then
+                	results=$(ldapsearch -LLL -ZZ -x -h ldap01.hpc.lsu.edu  -D uid=$admid,ou=Admins,ou=People,dc=hpc,dc=lsu,dc=edu -w "$ldappasswd" -b dc=hpc,dc=lsu,dc=edu "uid=$uid"  2>&1)
+       		else
+                	results=$(ldapsearch -LLL -ZZ -x -h lonildap01.hpc.lsu.edu  -D uid=$admid,ou=People,ou=Admins,dc=loni,dc=org -w "$ldappasswd" -b dc=loni,dc=org "uid=$uid" 2>&1)
+        	fi
+        	index=$(echo $index-1|bc)
     	done
-	if [[ `echo "$results" |grep "ldap_bind"` ]]; then
-                echo Passwd failed 3 times!$'\n'
-                exit 1
-	elif [[ ! `echo "$results" |grep "dn"` ]]; then 
+
+	if [[ ! `echo "$results" |grep "dn"` ]]; then 
 		echo user $uid does not exist, abort! $'\n' 
-		exit 1
+		Stop	
    	fi
+
 	#check if admin 
 	if [[ `echo "$results" |grep "Admins"` && "$action" == "disable" ]]; then
                 echo $uid belongs to Admins group, abort! $'\n'
-                exit 1
+                Stop
         fi
+
+	#Get the description of the user
    	if [[ `echo "$results" |grep "description:"` ]]; then
 		des=$(echo "$results" | awk -v c=0 '{if($1=="description:") c=1; else if (c>0 && substr($0, 0, 1)==" ") c++; else c=0; if (c>0) print $0}' |tr "\n" "_" | sed -e 's/\_\ //g; s/\_//g'| awk -v FS="description:" '{print $2}')
 		des=$(echo $des)    #trim white space
         else   des=''
         fi
+
 	if [[ `echo "$results" |grep -w "\b$uid\b"` ]]; then
         	if [[ `echo "$results" |grep "DisabledAccounts"`&& $action == "disable" ]]; then
                 	echo $'\n'$uid is already disabled in $category LDAP, Abort! $'\n'
-                	exit 1
+                	Stop
         	elif [[ ! `echo "$results" |grep "DisabledAccounts"`&& $action == "reenable" ]]; then
                 	echo $'\n'$uid is already alive in $category LDAP, Abort! $'\n'
-               	 	exit 1
+               	 	Stop
         	else    
       			u_info=$(echo "$results"|grep -v "Enter LDAP Password"| grep -v "objectClass"|grep -v "userPassword") 	
                 	echo $'\n'"$u_info" $'\n'$'\n' 
@@ -252,6 +287,59 @@ Check(){
 		fi 
    	fi
 	
+}
+
+Perform_modification(){
+
+log="ldap_bind"
+
+# Interactive for individual mode
+
+if [[ $individual ]]; then
+
+index=5
+ldappasswd2=
+#while [[ `echo $log |grep "ldap_bind"` &&  $index >0 ]];
+while [[ "$ldappasswd" != "$ldappasswd2" && $index >0 ]];
+    do
+        echo Enter LDAP passwd to COMMIT, followed by return
+	read -es ldappasswd2 
+        index=$(echo $index-1|bc)
+    done
+
+#if [[ `echo $log |grep "ldap_bind"` ]]; then
+if [[ "$ldappasswd" != "$ldappasswd2" ]]; then
+        echo Passwd failed 5 times! quit for now!$'\n'
+        exit 1
+fi
+
+fi
+
+if [[ $category == "hpc" ]]; then
+  log=$(echo -e $ldif | ldapmodify -ZZ -h ldap01.hpc.lsu.edu  -w "$ldappasswd" -x -D uid=$admid,ou=Admins,ou=People,dc=hpc,dc=lsu,dc=edu 2>&1)
+else
+  log=$(echo -e $ldif | ldapmodify -ZZ -h lonildap01.hpc.lsu.edu -w "$ldappasswd" -x -D uid=$admid,ou=People,ou=Admins,dc=loni,dc=org 2>&1)
+fi
+
+#check if sucessful
+declare -a errorarr=("No such object" "attribute or value exists" "invalid attribute syntax" "no such attribute" "insufficient access rights", "wrong attributeType")
+for error in "${errorarr[@]}"
+do
+        if [[ `echo $log|grep "\b$error\b"` ]];then
+                echo Failed due to "$error". Please investigate! $'\n'
+                Stop 
+        fi
+done
+echo Successfully Done! $'\n'
+
+}
+
+Stop(){
+  if [[ $batch ]]; then
+    return 1
+  else
+    exit 1
+  fi
 }
 
 #********************end of functions***************************
@@ -262,10 +350,16 @@ if [[ ! "$#" || "$1" == "-h" ]]; then
 fi
 
 if [[ "$#" != 6 ]]; then
-        echo Not enough parameters 
+        echo Check command line parameters 
         Usage
         exit 1
 fi
+
+uid=
+file=
+
+individual=
+batch=
 
 while (( "$#" )); 
 do
@@ -276,6 +370,11 @@ do
                 ;;
         -u)
                 uid=$2
+		individual=1
+                ;;
+        -b)
+                file=$2
+		batch=1
                 ;;
         -g)
                 type=$2
@@ -286,6 +385,17 @@ do
         esac
         shift 2
 done
+
+if [[ $individual && $batch ]]; then
+	echo The -u and -b flags cannot be used at the same time!
+	Usage
+	exit 1
+fi
+
+if [[ ! -f "$file" && $batch ]]; then
+	echo Cannot find the list $file! Please make sure the path and file name are correct.
+	exit 1
+fi
 
 declare -a typearr=(hpc loni teragrid xsede)
 element=$(echo  ${typearr[@]}|grep  "\b$type\b")
@@ -300,6 +410,7 @@ if [[ "$action" != "disable" && "$action" != "reenable" ]]; then
         Usage
         exit 1
 fi
+
 #block XSESE accounts  
 if [ "$type" == "xsede" ]; then
 	echo  $uid is a XSESED user, Abort! $'\n'
@@ -323,56 +434,48 @@ elif [[ "$type" == "xsede" || $type == "hpc" ]]; then
 
 fi
 
-# check user info 
-Check 
-
-index=3
-reason=""
-#blank reason
-while [[ $reason != *[!\ ]*  &&  $index >0 ]];
-do
-	read -p "Please provide reason to $action the account: "  reason
-	
-	index=$(echo $index-1|bc)
-done
-if [ ! $index ]; then
-	echo No input for reason to $action the account. abort!
-	exit 1
-else 
-	reason=$(echo $reason)
-fi
+# Get and cache the LDAP passwd
+Getpasswd
 
 
-Deactivate_accounts 
-
-log="ldap_bind"
-index=5
-while [[ `echo $log |grep "ldap_bind"` &&  $index >0 ]];
+if [[ $batch ]]; then
+# Batch mode
+  while IFS=: read -r uid reason
     do
-        echo Enter LDAP passwd to COMMIT, followed by return
-        if [[ $category == "hpc" ]]; then
-		log=$(echo -e $ldif | ldapmodify -ZZ -h ldap01.hpc.lsu.edu  -W -x -D uid=$admid,ou=Admins,ou=People,dc=hpc,dc=lsu,dc=edu 2>&1)
-        else
-		#log=$(echo -e $ldif | ldapmodify -ZZ -h ldap01.sys.loni.org -W -x -D uid=$admid,ou=People,ou=Admins,dc=loni,dc=org 2>&1)
-		log=$(echo -e $ldif | ldapmodify -ZZ -h lonildap01.hpc.lsu.edu -W -x -D uid=$admid,ou=People,ou=Admins,dc=loni,dc=org 2>&1)
-        fi
+      echo Disabling $uid for: $reason
+      
+      Check
+
+      Assemble_modification
+
+      Perform_modification
+
+      sleep 5
+
+    done < "$file"
+
+elif [[ $individual ]]; then
+# Individual mode
+  Check
+
+  index=3
+  reason=""
+  #blank reason
+  while [[ $reason != *[!\ ]*  &&  $index >0 ]];
+    do
+        read -p "Please provide reason to $action the account: "  reason
+
         index=$(echo $index-1|bc)
     done
+  if [ ! $index ]; then
+        echo No input for reason to $action the account. abort!
+        exit 1
+  else
+        reason=$(echo $reason)
+  fi			
 
-if [[ `echo $log |grep "ldap_bind"` ]]; then
-	echo Passwd failed 5 times! quit for now!$'\n'
-	exit 1
+  Assemble_modification
+
+  Perform_modification
+
 fi
-
-#check if sucessful                   
-declare -a errorarr=("No such object" "attribute or value exists" "invalid attribute syntax" "no such attribute" "insufficient access rights", "wrong attributeType")
-for error in "${errorarr[@]}"
-do
-        if [[ `echo $log|grep "\b$error\b"` ]];then
-                echo Failed duo to "$error". Please investigate! $'\n'
-                exit 1
-        fi
-done
-echo Successfully Done! $'\n'
-
-
